<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: "cybersource"
            };
            layout([
                {
                    component: "Magento_Cybersource/js/view/payment/method-renderer/multishipping/cybersource",
                    name: "payment_method_cybersource",
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
