<?php

/** @var $block Magento\Catalog\Block\FrontendStorageManager */
?>
<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "storage-manager": {
                            "component": "Magento_Catalog/js/storage-manager",
                            "appendTo": "<?= $block->escapeJs($block->getParentComponentName()) ?>",
                            "storagesConfiguration" : <?= /* @noEscape */ $block->getConfigurationJson() ?>
                        }
                    }
                }
            }
        }
</script>
