<?php
// phpcs:disable Magento2.Files.LineLength
?>
<?php /* @var $block \Magento\AdvancedCheckout\Block\Adminhtml\Sku\Errors\Grid\Description */ ?>
<?php $_item = $block->getItem() ?>
<?php $_product = $block->getItem()->getProduct() ?>
<?php $_skuAttrEscaped = $block->escapeHtmlAttr($_item->getSku()) ?>
<div id="<?= /* @noEscape - escaped in var declaration */ 'sku_' . $_skuAttrEscaped ?>" class="sku-failed-item">
    <?php if ($_product->getName()) : ?>
        <p><strong><?= $block->escapeHtml($_product->getName()) ?></strong></p>
    <?php endif ?>

    <p><strong><?= $block->escapeHtml(__('SKU: ')) ?></strong> <?= $block->escapeHtml($_item->getSku()) ?></p>

    <div class="messages">
        <div class="message message-notice" data-role="message-notice">
            <?= $block->escapeHtml($block->getErrorMessage($_item)) ?>
        </div>
    </div>

    <div class="sku-configure-button">
        <?= $block->getConfigureButtonHtml() ?>
    </div>

    <?php if ($_item->getQtyMaxAllowed()) : ?>
        <?= $block->escapeHtml(__('Only <span id="%1_max_allowed">%2</span> in stock', $_skuAttrEscaped, (float)$_item->getQtyMaxAllowed()), ['span']) ?>
    <?php endif ?>
    <input type="hidden" name="sku" value="<?= /* @noEscape - escaped in var declaration */ $_skuAttrEscaped ?>"/>
    <input type="checkbox" name="<?= $block->escapeHtmlAttr($block->getSourceId()) ?>" value="<?= /* @noEscape - escaped in var declaration */ $_skuAttrEscaped ?>" checked="checked" style="display:none"/>
</div>
