#!/usr/bin/env php
<?php

$mtfRoot = dirname(__DIR__);
$mtfRoot = str_replace('\\', '/', $mtfRoot);
define('MTF_PHPUNIT_FILE', $mtfRoot . DIRECTORY_SEPARATOR . 'phpunit.xml');
include $mtfRoot . '/vendor/magento/mtf/utils/mtf';
