<?php

/** @var \Magento\Review\Block\Adminhtml\Rating\Summary $block */
?>
<?php if ($block->getRatingSummary()->getCount()) : ?>
    <div class="rating-box">
        <div class="rating" style="width:<?= /* @noEscape */ ceil($block->getRatingSummary()->getSum() / ($block->getRatingSummary()->getCount())) ?>%;"></div>
    </div>
<?php else : ?>
    <?= $block->escapeHtml(__("Rating isn't Available")) ?>
<?php endif; ?>
