<div class="block block-comments">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Quote Comments')) ?></strong>
    </div>
    <div class="block-content">
        <div class="comments-field field-row" data-role="attach-wrapper">
            <?php
                /** @var  $block \Magento\NegotiableQuote\Block\Quote\Comments*/
                $disable = !$block->canEdit() ? ' _disabled' : '';
            ?>
            <form action="<?= $block->escapeUrl($block->getUrl('negotiable_quote/quote/send')) ?>"
                  data-action="comment-form"
                  method="post"
                  enctype="multipart/form-data">
                <label class="comments-field-label"
                       for="negotiation_comment"><?= $block->escapeHtml(__('Add your comment')) ?></label>
                <div class="comments-field-control">
                        <textarea name="comment"
                            <?php if (!$block->isAllowedManage()) : ?>
                                disabled="disabled"
                            <?php endif; ?>
                                  class="negotiation-control-textarea<?= /* @noEscape */ $disable ?>"
                                  rows="3"
                            <?= /* @noEscape */ !$block->canEdit() ? 'disabled' : '' ?>
                                  cols="5"
                                  id="negotiation_comment"></textarea>
                </div>
                <div data-mage-init='{"Magento_NegotiableQuote/js/quote/add-files": {
                                            "maxSizeB" : "<?= $block->escapeJs($block->getMaxFileSize()) ?>",
                                            "maxSizeMb" : "<?= $block->escapeJs($block->getMaxFileSizeMb()) ?>",
                                            "extensions" : "<?= $block->escapeJs($block->getAllowedExtensions()) ?>",
                                            "modal" : "true"
                                            }}'
                     class="field-attachment<?= /* @noEscape */ $disable ?>"
                     data-role="send-files"
                     data-progress="">
                    <?php if ($block->isAllowedManage()) : ?>
                    <label data-mage-init='{"Magento_NegotiableQuote/js/quote/add-file": {}}'
                           for="add-file-0"
                            <?= /* @noEscape */ $block->canEdit() ? 'tabindex="0"' : '' ?>>
                        <input name="files[0]" data-role="add-file" id="add-file-0" type="file">
                        <?= $block->escapeHtml(__('Attach file')) ?>
                    </label>
                    <?php endif; ?>
                </div>
                <input type="hidden" name="quote_id" value="<?= (int) $block->getQuote()->getId() ?>"/>
                <?= $block->getBlockHtml('formkey') ?>
            </form>
            <div class="attachments-list" data-role="added-files"></div>
            <div class="attachments-list" data-role="history-added-files"></div>
        </div>
    </div>
</div>
