<?php

/** @var  $block \Magento\NegotiableQuote\Block\Quote\Comments */
?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Comments')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="quote-comments-block">
            <?php foreach ($block->getQuoteComments() as $comment) : ?>
                <?php /** @var $comment \Magento\NegotiableQuote\Model\Comment */?>
                <div class="comments-block-item">
                    <span class="comments-block-item-date-time">
                        <?= /* @noEscape */ $block->formatDate(
                            $comment->getCreatedAt(),
                            \IntlDateFormatter::MEDIUM,
                            true
                        ) ?>
                        <?= $block->escapeHtml($block->getCommentCreator($comment)) ?>
                    </span>
                    <div class="comments-block-item-comment">
                        <?php if ($comment->getIsDecline()) : ?>
                            <b class="comments-request-declined">
                                <?= $block->escapeHtml(__('Request Declined. Reason: ')) ?>
                            </b>
                        <?php endif ?>
                        <?= $block->escapeHtml(nl2br($comment->getComment())) ?>
                    </div>
                    <?php $attachments = $block->getCommentAttachments($comment->getEntityId()) ?>
                    <?php if ($attachments->count() > 0) : ?>
                        <div class="attachments-list">
                            <?php foreach ($attachments as $file) : ?>
                                <?php /** @var $file \Magento\NegotiableQuote\Model\CommentAttachment */ ?>
                                <span class="attachments-item">
                                    <a href="<?= $block->escapeUrl($block->getAttachmentUrl($file->getAttachmentId())) ?>"
                                       title="<?= $block->escapeHtmlAttr($file->getFileName()) ?>">
                                        <?= $block->escapeHtml($file->getFileName()) ?></a>
                                </span>
                            <?php endforeach ?>
                        </div>
                    <?php endif ?>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</section>
