<?php

/**
 * @deprecated
 * @var $block \Magento\Backend\Block\Page\System\Config\Robots\Reset
 * @var $jsonHelper \Magento\Framework\Json\Helper\Data
 */
$jsonHelper = $this->helper(\Magento\Framework\Json\Helper\Data::class);
?>

<script>
    require([
        'jquery'
    ], function ($) {
        window.resetRobotsToDefault = function(){
            $('#design_search_engine_robots_custom_instructions').val(<?=
                /* @noEscape */ $jsonHelper->jsonEncode($block->getRobotsDefaultCustomInstructions())
            ?>);
        }
    });
</script>

<?= $block->getButtonHtml() ?>
