<?php
/**
 * @var $block \Magento\CompanyCredit\Block\Form\CompanyCredit
 */
?>
<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>" style="display: none">
    <div class="admin__field _required">
        <label for="po_number" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Purchase Order Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="po_number" name="payment[po_number]"
                   title="<?= $block->escapeHtml(__("Purchase Order Number")) ?>"
                   class="admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('po_number') ?>"/>
        </div>
    </div>
</fieldset>
