<?php /** @var $block Magento\NegotiableQuote\Block\Quote\Message */ ?>
<div id="messages">
    <?php if (!empty($block->getMessages())) : ?>
        <?php foreach ($block->getMessages() as $key => $message) : ?>
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                    <?= $block->escapeHtml($message) ?>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
