<?php

/* @var $block \Magento\RequisitionList\Block\Link\Lists */
?>
<!-- ko scope: 'requisition' -->
<!-- ko if: requisition().is_enabled-->
<li>
    <a href="<?= $block->escapeUrl($block->getHref()) ?>">
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
<!-- /ko -->
<!-- /ko -->
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "requisition": {
                        "component": "Magento_RequisitionList/js/requisition"
                    }
                }
            }
        }
    }
</script>
