<?php
/**
 * @var $block \Magento\CompanyCredit\Block\Adminhtml\Order\Message
 */
?>
<?php if ($block->isPayOnAccountMethod() && $block->getCredit()) : ?>
    <div class="wrap-messages" data-role="message-block">
        <div id="messages">
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                    <?php
                    if ($block->getCredit()->getAvailableLimit() < 0) {
                        echo $block->escapeHtml(
                            __(
                                '%1 has exceeded its credit limit (%2) by %3. Its outstanding balance, including this order, currently totals %4.',
                                $block->getCompanyName(),
                                $block->formatPrice($block->getCredit()->getCreditLimit()),
                                $block->formatPrice(-$block->getCredit()->getAvailableLimit()),
                                $block->formatPrice($block->getCredit()->getBalance())
                            )
                        );
                    } else {
                        echo $block->escapeHtml(
                            __(
                                'The credit limit for %1 is %2. Its outstanding balance, including this order, currently totals %3',
                                $block->getCompanyName(),
                                $block->formatPrice($block->getCredit()->getCreditLimit()),
                                $block->formatPrice($block->getCredit()->getBalance())
                            )
                        );
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
