<?php
// phpcs:disable Magento2.Files.LineLength
?>
<?php /* @var $block \Magento\AdvancedCheckout\Block\Adminhtml\Sku\Errors\AbstractErrors */ ?>
<div class="fieldset-wrapper admin__fieldset-wrapper">
    <div class="fieldset-wrapper-title admin__fieldset-wrapper-title">
        <span class="title" data-role="error-title"><?= $block->escapeHtml($block->getHeaderText(), ['span']) ?></span>
        <div class="actions">
            <?= $block->getButtonHtml($block->getAddButtonTitle(), 'addBySku.submitConfigured()', 'action-add') ?>
            <?= $block->getButtonsHtml() ?>
        </div>
    </div>
    <?= $block->getChildHtml() ?>
</div>

<script>
/* global productConfigure */
require([
    'jquery',
    'prototype',
    'Magento_Catalog/catalog/product/composite/configure'
], function (jQuery) {

    function checkoutSkuErrorsInit()
    {
        productConfigure.addListType('<?= $block->escapeJs($block->getListType()) ?>', {urlFetch: '<?= $block->escapeJs($block->escapeUrl($block->getConfigureUrl())) ?>'});
        <?= /* @noEscape */ $block->getAdditionalJavascript() ?>
    }

    if (jQuery(document).data('productConfigureInited')) {
        checkoutSkuErrorsInit();
    } else {
        jQuery(document).on('productConfigure:inited', checkoutSkuErrorsInit);
    }
});
</script>
