<?php
?>
<?php

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
// phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore

/* @var $block \Magento\GiftRegistry\Block\Customer\Address\Edit */
?>

<fieldset class="fieldset shipping_address">
    <legend class="legend"><span><?= $block->escapeHtml(__('Shipping Address')) ?></span></legend>
    <br />

    <?php if ($block->customerHasAddresses()) : ?>
        <div class="field address">
            <label for="address_type_or_id" class="label"><span><?= $block->escapeHtml(__('Select a shipping address from your address book or enter a new address.')) ?></span></label>
            <div class="control" data-shipping-address="<?= $block->getEntity()->getShippingAddress() ? 'true' : 'false' ?>">
                <?= $block->getAddressHtmlSelect('address_type_or_id') ?>
            </div>
        </div>
    <?php endif ?>

    <fieldset class="fieldset" id="shipping-new-address-form"<?php if ($block->customerHasAddresses()) :?> style="display: none;"<?php endif ?>>
        <?= $block->getLayout()->createBlock(Magento\Customer\Block\Widget\Name::class)->setObject($block->getAddress())->setFieldNameFormat('address[%s]')->toHtml() ?>

        <div class="field company">
            <label for="address:company" class="label"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text" id="address:company" name="address[company]" value="<?= $block->escapeHtml($block->getAddress()->getCompany()) ?>" title="<?= $block->escapeHtmlAttr(__('Company')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('company')) ?>"/>
            </div>
        </div>

        <?php $_streetValidationClass = $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('street')); ?>
        <div class="field address street required">
            <label for="address:street1" class="label"><span><?= $block->escapeHtml(__('Address')) ?></span></label>
            <div class="control">
                <input type="text" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" name="address[street][]" id="address:street1" value="<?= $block->escapeHtml($block->getAddress()->getStreetLine(1)) ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>" />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper(Magento\Customer\Helper\Address::class)->getStreetLines(); $_i <= $_n; $_i++) :?>
                        <div class="field additional no-label">
                            <div class="control">
                                <input type="text" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" name="address[street][]" id="address:street<?= /* @noEscape */ $_i ?>" value="<?= $block->escapeHtml($block->getAddress()->getStreetLine($_i)) ?>" class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <div class="field address city required">
            <label for="address:city" class="label"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text" title="<?= $block->escapeHtmlAttr(__('City')) ?>" name="address[city]" value="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('city')) ?>" id="address:city"/>
            </div>
        </div>
        <div class="field address region required">
            <label for="address:region" class="label"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select id="address:region_id" name="address[region_id]" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" style="display:none;">
                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                </select>
                <input type="text" id="address:region" name="address[region]" value="<?= $block->escapeHtml($block->getAddress()->getRegion()) ?>" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('region')) ?>" style="display:none;" />
            </div>
        </div>

        <div class="field address postcode required">
            <label for="address:postcode" class="label"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="control">
                <input type="text" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" name="address[postcode]" id="address:postcode" value="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('postcode')) ?>" data-validate="{'required':true, 'validate-zip-international':true}"/>
            </div>
        </div>
        <div class="field address country required">
            <label for="address:country_id" class="label"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect($block->getAddress()->getCountryId(), 'address[country_id]', 'address:country_id') ?>
            </div>
        </div>

        <div class="field address telephone required">
            <label for="address:telephone" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text" name="address[telephone]" value="<?= $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('telephone')) ?>" id="address:telephone"/>
            </div>
        </div>
        <div class="field address fax">
            <label for="address:fax" class="label"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
            <div class="control">
                <input type="text" name="address[fax]" value="<?= $block->escapeHtml($block->getAddress()->getFax()) ?>" title="<?= $block->escapeHtmlAttr(__('Fax')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(Magento\Customer\Helper\Address::class)->getAttributeValidationClass('fax')) ?>" id="address:fax"/>
            </div>
        </div>
    </fieldset>
</fieldset>
<script type="text/x-magento-init">
    {
        "#address\\:country_id": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= ($block->getConfig('general/region/display_all') ? 'true' : 'false') ?>,
                "regionListId": "#address\\:region_id",
                "regionInputId": "#address\\:region",
                "postcodeId": "#address\\:postcode",
                "regionJson": <?= /* @noEscape */ $this->helper(Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= /* @noEscape */ $block->getAddress()->getRegionId() ?>"
            }
        }
    }
</script>
