<script>
require(['prototype'], function(){

//<![CDATA[
OptionTemplateCountry =
    '<div class="field field-region">'+
        '<label class="label" for=""><span><?= $block->escapeJs($block->escapeHtml(__('Show Region'))) ?></label>'+
        '<div class="control"><?= $block->getRegionShowSelectHtml() ?></div>'+
    '</div>';

selectCountryType = {
    add : function(data) {
        if (data.show_region) {
            $A($(data.prefix+'_attribute_'+data.id+'_show_region').options).each(function(option){
                if (option.value==data.show_region) option.selected = true;
           });
        }
    }
}
//]]>

});
</script>
