<?php

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(\Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
/** @var \Magento\NegotiableQuote\Helper\Quote $quoteHelper */
$quoteHelper = $this->helper(\Magento\NegotiableQuote\Helper\Quote::class);
$baseCurrency = $item->getQuote()->getCurrency()->getBaseCurrencyCode();
$quoteCurrency = $item->getQuote()->getCurrency()->getQuoteCurrencyCode();
$productUrl = $block->hasProductUrl() ? $block->getProductUrl() : '';
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($productUrl) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?php if ($block->hasProductUrl()) : ?>
                </a>
            <?php else : ?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) : ?>
                        <a href="<?= $block->escapeUrl($productUrl) ?>">
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        </a>
                    <?php else : ?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($options = $block->getOptionList()) : ?>
                    <dl class="item-options">
                        <?php foreach ($options as $option) : ?>
                            <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                            <dt><?= $block->escapeHtml($option['label']) ?></dt>
                            <dd>
                                <?php if (isset($formatedOptionValue['full_view'])) : ?>
                                    <?= /* @noEscape */ $formatedOptionValue['full_view'] ?>
                                <?php else : ?>
                                    <?= /* @noEscape */ $formatedOptionValue['value'] ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <?php if ($messages = $block->getMessages()) : ?>
                    <?php foreach ($messages as $message) : ?>
                        <div class="cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) : ?>
                    <?= $addInfoBlock->setItem($item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <td class="col sku" data-th="<?= $block->escapeHtmlAttr(__('SKU')) ?>">
            <?= $block->escapeHtml($product->getSku()) ?>
        </td>


        <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
            <?= /* @noEscape */ $quoteHelper->getFormattedCatalogPrice($item, $quoteCurrency, $baseCurrency) ?>
        </td>

        <td class="col stock" data-th="<?= $block->escapeHtmlAttr(__('Stock')) ?>">
            <?= /* @noEscape */ number_format($quoteHelper->getStockForProduct($item)) ?>
        </td>

        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty">
                <label class="label" for="cart-<?= (int) $item->getId() ?>-qty">
                    <span><?= $block->escapeHtml(__('Qty')) ?></span>
                </label>
                <div class="control qty">
                    <input id="cart-<?= (int) $item->getId() ?>-qty"
                           name="cart[<?= (int) $item->getId() ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($item->getSku()) ?>"
                           value="<?= (int) $block->getQty() ?>"
                           type="number"
                           size="4"
                           title="<?= $block->escapeHtmlAttr(__('Ordered')) ?>"
                           class="input-text qty"
                           maxlength="12"
                           data-validate='{
                                    "validate-number": true,
                                    "validate-greater-than-zero": true,
                                    "required": true,
                                    "integer": true
                                    }'
                            <?= /* @noEscape */ !$quoteHelper->isSubmitAvailable() ? 'disabled' : '' ?>
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                            <?php if (!$quoteHelper->isAllowedManage()) : ?>
                                disabled="disabled"
                            <?php endif; ?>
                           data-role="cart-item-qty"/>
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) : ?>
                <span class="cart msrp subtotal">--</span>
            <?php else : ?>
                <?= /* @noEscape */ $quoteHelper->getItemTotal($item, $quoteCurrency, $baseCurrency) ?>
            <?php endif; ?>
        </td>
        <td class="col delete">
            <div class="actions-toolbar<?= /* @noEscape */ $quoteHelper->isSubmitAvailable()?'':' _disabled' ?>">
                <?= /* @noEscape */ $block->getActions($item) ?>
            </div>
        </td>
    </tr>
</tbody>
