<?php
?>
<?php
/** @var Magento\Rma\Block\Adminhtml\Rma\Edit\Js $block */
?>
<script>
//<![CDATA[
require(['prototype', 'Magento_Rma/rma', 'domReady!'], function() {
    rma.setLoadAttributesUrl('<?= $block->escapeJs($block->escapeUrl($block->getLoadAttributesUrl())) ?>');
    rma.setLoadSplitLineUrl('<?= $block->escapeJs($block->escapeUrl($block->getLoadSplitLineUrl())) ?>');
    rma.setDeleteLineLabel('<?= $block->escapeJs($block->escapeHtml(__('Delete Line'))) ?>');
    $$('a.action-item-details').each(function (obj) {
        obj.observe('click', rma.itemDetailsRowClick.bind(rma))
    });
    $$('a.action-item-split-line').each(function (obj) {
        obj.observe('click', rma.itemSplitLineRowClick.bind(rma))
    });
    $$('a.item_reason_other').each(function (obj) {
        obj.observe('click', rma.itemReasonOtherRowClick.bind(rma))
    });
    rma.setFormKey('<?= /* @noEscape */ $block->getFormKey() ?>');
    rma.setLoadShippingMethodsUrl('<?= $block->escapeJs($block->escapeHtml($block->getLoadShippingMethodsUrl())) ?>');
    rma.setLoadPslUrl('<?= $block->escapeJs($block->escapeHtml($block->getLoadPslUrl())) ?>');
    if ($('get-shipping-method-and-rates')) {
        $('get-shipping-method-and-rates').observe('click', rma.showShippingMethods.bind(rma));
    }
    $$('input.rowId').each(function (el, val) {
        rma.getAjaxData($(el).value, true);
    });
    rma.callLoadProductsCallback();
});
//]]>
</script>
