<?php

/**
 * @var $block \Magento\Catalog\Block\Adminhtml\Category\Edit
 */
?>
<div data-id="information-dialog-category" class="messages" style="display: none;">
    <div class="message message-notice">
        <div><?= $block->escapeHtml(__('This operation can take a long time')) ?></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "categoryForm": {"refreshUrl": "<?= $block->escapeJs($block->escapeUrl($block->getRefreshPathUrl())) ?>"}
        }
    }
</script>
