<?php

/** @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Form\Account */
?>

<div class="admin__page-section-title <?= $block->escapeHtmlAttr($block->getHeaderCssClass()) ?>">
    <span class="title"><?= $block->escapeHtml($block->getHeaderText()) ?></span>
    <div class="actions"></div>
</div>
<div id="customer_account_fields" class="admin__page-section-content">
    <?= $block->getForm()->getHtml() ?>
</div>

<script>
    require(["prototype", "Magento_Sales/order/create/form"], function(){
        order.accountFieldsBind($('customer_account_fields'));
    });
</script>
