<?php
/**
 * @var $block \Magento\CompanyCredit\Block\Form\CompanyCredit
 */
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?= /* @noEscape */ $methodCode ?>"
          id="payment_form_<?= /* @noEscape */ $methodCode ?>" style="display: none">
    <div class="field number required">
        <label for="po_number" class="label">
            <span><?= $block->escapeHtml(__('Purchase Order Number')) ?></span>
        </label>
        <div class="control">
            <input type="text" id="po_number" name="payment[po_number]"
                   title="<?= $block->escapeHtml(__('Purchase Order Number')) ?>"
                   class="input-text"
                   value="<?= $block->escapeHtml($block->getInfoData('po_number')) ?>" />
        </div>
    </div>
</fieldset>
