<?php

/* @var $block \Magento\Customer\Block\CustomerScopeData */
?>
<script type="text/x-magento-init">
<?= /* @noEscape */ $block->encodeConfiguration([
        '*' => ['Magento_Customer/js/invalidation-processor' => [
            'invalidationRules' => [
                'website-rule' => [
                    'Magento_Customer/js/invalidation-rules/website-rule' => [
                        'scopeConfig' => [
                            'websiteId' => $block->getWebsiteId(),
                        ]
                    ]
                ]
            ]
        ]],
    ]);
?>
</script>
