<?php

/** @var \Magento\Banner\Block\Ajax\Data $block */
?>
<script type="text/x-magento-init">
<?= /* @noEscape */ $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode([
        '*' => ['Magento_Banner/js/model/banner' => [
            'sectionLoadUrl' => $block->escapeUrl($block->getCustomerDataUrl('banner/ajax/load')),
            'cacheTtl' => $block->getCacheTtl()
        ]],
    ]);
?>
</script>
