<?php

/**
 * @var \Magento\GiftCardAccount\Block\Adminhtml\Giftcardaccount $block
 */

$source = $block->getSource();
$block->setPriceDataObject($source);
?>

<?php if ((float) $source->getGiftCardsAmount()) : ?>
    <tr>
        <td class="label"><?= $block->escapeHtml(__('Gift Cards')) ?></td>
        <td>
            <?= /* @noEscape */ $block->displayPrices(-$source->getBaseGiftCardsAmount(), -$source->getGiftCardsAmount()) ?>
        </td>
    </tr>
<?php endif; ?>
