<?php
?>
<script>
    require([
        'uiLayout',
        'jquery'
    ], function (layout, $) {
        $(function () {
            var paymentMethodData = {
                method: 'braintree_paypal'
            };
            layout([
                {
                    component: 'Magento_Braintree/js/view/payment/method-renderer/multishipping/paypal',
                    name: 'payment_method_braintree_paypal',
                    method: paymentMethodData.method,
                    item: paymentMethodData
                }
            ]);

            $('body').trigger('contentUpdated');
        })
    })
</script>
<!-- ko template: getTemplate() --><!-- /ko -->
