<?php
    $wishlistItems = $block->getWishlistItems();
?>

<div class="block block-wishlist-info">
    <div class="actions">
        <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    </div>
    <div class="block-content">
        <dl class="items">
            <dt class="item-title">
                <?= $block->escapeHtml(__('Owner')) ?>
            </dt>
            <dd class="item-content">
                <?= $block->escapeHtml($block->getWishlistOwner()->getName()) ?>
            </dd>
            <dt class="item-title">
                <?= $block->escapeHtml(__('Name')) ?>
            </dt>
            <dd class="item-content">
                <?= $block->escapeHtml($block->getWishlistInstance()->getName()) ?>
            </dd>
            <dt class="item-title">
                <?= $block->escapeHtml(__('Updated')) ?>
            </dt>
            <dd class="item-content">
                <?= /* @noEscape */ $block->formatDate($block->getWishlistInstance()->getUpdatedAt(), \IntlDateFormatter::MEDIUM) ?>
            </dd>
        </dl>
    </div>
</div>

<div class="block block-wishlist-info-items">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Wish List Items')) ?></strong>
    </div>
    <div class="block-content">
        <form method="post" action="<?= $block->escapeUrl($block->getToCartUrl()) ?>" id="wishlist-info-form"
              data-mage-init='{"wishlist":{
          "infoList":true,
          "checkBoxValidationMessage":"<?= $block->escapeHtmlAttr(__('You must select items to add to the cart.')) ?>"}
          }' class="form wishlist">
            <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
            <?= $block->getChildHtml('items') ?>
            <?php if (count($wishlistItems) && $block->isSaleable()) : ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action tocart"><span><?= $block->escapeHtml(__('Add to Cart')) ?></span></button>
                    </div>
                    <div class="secondary">
                        <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="action back"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
                    </div>
                </div>
            <?php endif; ?>
        </form>
    </div>
</div>
