<?php
/** @var \Magento\DataServices\Block\Context $block */
$viewModel = $block->getViewModel();
?>

<script>
    window.dsDataLayer.page = {
        pageType: "<?= /* @noEscape */ $block->getData('page_type'); ?>",
        action: "<?= /* @noEscape */ $block->getData('step_name'); ?>"
    };
    window.dsDataLayer.cart = {
        cartId: <?= /* @noEscape */ $block->getCartId(); ?>
    };
    window.dsDataLayer.order = {
        orderId: "<?= /* @noEscape */ $viewModel->getOrderId(); ?>"
    };
</script>
