<?php
?>
<?php
/**
 * @var $block \Magento\Rma\Block\Adminhtml\Rma\Edit\Tab\General\Returnaddress
 */

$customerLink = $block->getCustomerLink();
?>
<div class="admin__page-section-item order-return-address">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $block->escapeHtml(__('Return Address')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <address><?= /* @noEscape */ $block->getReturnAddress() ?></address>
    </div>
</div>
