<?php
?>
<?php $_source  = $block->getSource() ?>
<?php $block->setPriceDataObject($_source) ?>

<tr>
    <td class="label">
        <strong><big>
        <?php if ($block->getGrandTotalTitle()) : ?>
            <?= $block->escapeHtml($block->getGrandTotalTitle()) ?>
        <?php else : ?>
            <?= $block->escapeHtml(__('Grand Total')) ?>
        <?php endif; ?>
        </big></strong>
    </td>
    <td class="emph"><big><?= /* @noEscape */ $block->displayPriceAttribute('grand_total', true) ?></big></td>
</tr>
