<?php

/** @var $block \Magento\SharedCatalog\Block\Adminhtml\SharedCatalog\Wizard\State\Category\Tree */
?>
<div data-role="spinner" data-component="shared_catalog_state_category_tree"
     class="jstree-spinner-helper admin__data-grid-loading-mask">
    <div class="spinner">
        <span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span>
    </div>
</div>
<div data-role='jstree-shared-catalog' data-bind="scope: 'shared_catalog_state_category_tree'">
    <div class="shared-catalog-tree-controls">
        <button class="action" data-action="expand-state-tree" type="button"
                data-role="button-expand-tree" data-button-state="collapse"></button>
    </div>
    <div data-role='jstree-shared-catalog-state-container' class="jstree-shared-catalog-state" data-bind="afterRender: initTree"></div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "shared_catalog_state_category_tree": {
                        "component": "Magento_SharedCatalog/js/wizard/state/category/tree",
                        "treeContainerSelector": "[data-role='jstree-shared-catalog-state-container']",
                        "provider": "shared_catalog_state_category_tree.provider"
                    },
                    "shared_catalog_state_category_tree.provider": {
                        "component": "Magento_Ui/js/grid/provider",
                        "storageConfig": {
                            "cacheRequests": false
                        },
                        "update_url": "<?= $block->escapeJs($block->getTreeUrl()) ?>"
                    }
                }
            }
        }
    }
</script>
