<?php

/** @var $block Magento\GiftRegistry\Block\Customer\Checkout\Multishipping */
?>

<?php if ($block->getEnabled() && $block->getItems()) :?>
<script id="address-option-tmpl" type="text/x-magento-template">
    <option value="<%- data._value_ %>"><%- data._text_ %></option>
</script>

<script type="text/x-magento-init">
    <?php $selectedGrAddressesIndexes = $block->getGiftregistrySelectedAddressesIndexes(); ?>
    <?php $selectedGrAddressesIndexesJson = '[' . implode(',', $selectedGrAddressesIndexes) . ']'; ?>

    <?php $registryItems = []; ?>
    <?php foreach ($block->getItems() as $itemId => $registryItem) :?>
        <?php $wrappedRegistryItem = '{"item": '
            . $block->escapeJs((string)$itemId)
            . ', "address":'
            . $block->escapeJs((string)$registryItem['item_id'])
            . '}';
        ?>
        <?php array_push($registryItems, $wrappedRegistryItem); ?>
    <?php endforeach ?>
    <?php $registryItemsJson = '[' . implode(',', $registryItems) . ']'; ?>

    {
        "#multiship-addresses-table": {
            "addressOption": {
                "registryItems": <?= /* @noEscape */ $registryItemsJson ?>,
                "addressItemPrefix": "<?= /* @noEscape */ $block->getAddressIdPrefix() ?>",
                "selectedAddressIndices": <?= /* @noEscape */ $selectedGrAddressesIndexesJson ?>
            }
        }
    }
</script>

<?php endif; ?>
