<?php

/**
 * @var $block \Magento\SharedCatalog\Block\Adminhtml\SharedCatalog\Wizard\StepsWizard
 */
?>
    <div data-role="steps-wizard-main" class="steps-wizard"
         data-bind="scope: '<?= /* @noEscape */ $block->getComponentName() ?>'">
        <div data-role="messages" class="messages"></div>

        <div data-role="steps-wizard-controls" class="steps-wizard-navigation">
            <ul class="nav-bar">
                <?php
                foreach ($block->getSteps() as $step) : ?>
                    <li data-role="collapsible"
                        data-bind="css: { 'active':
                            selectedStep() == '<?= /* @noEscape */ $step->getComponentName() ?>'
                        }">
                        <a href="#<?= /* @noEscape */ $step->getComponentName() ?>"
                           data-bind="click: showSpecificStep">
                            <?= /* @noEscape */ $step->getCaption() ?>
                        </a>
                    </li>
                    <?php
                endforeach; ?>
            </ul>
            <div class="nav-bar-outer-actions">
                <div class="action-wrap" data-role="closeBtn">
                    <button type="button"
                            class="action-cancel action-tertiary" data-bind="click: close">
                        <span><?= $block->escapeHtml(__('Cancel')) ?></span>
                    </button>
                </div>
                <div class="action-wrap action-wrap-prev" data-role="step-wizard-prev">
                    <button type="button"
                            class="action-default action-back-step"
                            data-bind="click: back, css: { 'disabled': disabled}">
                        <span><?= $block->escapeHtml(__('Back')) ?></span>
                    </button>
                </div>
                <div class="action-wrap action-wrap-next" data-role="step-wizard-next">
                    <button type="button"
                            class="action-default action-primary action-next-step" data-bind="click: next">
                        <span><?= $block->escapeHtml(__('Next')) ?></span>
                    </button>
                </div>
            </div>
        </div>

        <?= $block->getChildHtml('sharedCatalog.messages.notification.wizard') ?>

        <div data-role="steps-wizard-tab">
            <?php
            foreach ($block->getSteps() as $step) : ?>
                <div data-bind="visible: selectedStep() == $element.id"
                     class="content" id="<?= /* @noEscape */ $step->getComponentName() ?>"
                     data-role="content">
                    <?= /* @noEscape */ $step->getContent() ?>
                </div>
                <?php
            endforeach; ?>
        </div>
    </div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                        "<?= $block->escapeJs($block->getComponentName()) ?>": {
                            "component": "Magento_SharedCatalog/js/step-wizard",
                            "initData": <?= /* @noEscape */ $block->getInitDataAsJson() ?>,
                            "stepsNames": <?= /* @noEscape */ $block->getStepComponentsAsJson() ?>
                        }
                    }
                }
            }
    }
</script>
