<?php
/**
 * @var $block \Magento\NegotiableQuote\Block\Adminhtml\Quote\View\Info
 */
?>
<div class="wrap-messages" data-role="message-block">
    <?php if ($block->canEdit()) : ?>
        <?php $isShown = ($block->hasQuoteChanges() || $block->hasUnconfirmedChanges()) ?>
        <div id="quote-changed-message"<?= /* @noEscape */ !$isShown ? ' class="hidden"' : '' ?>>
            <div class="message message-notice notice">
                <div data-ui-id="messages-message-notice">
                    <?= $block->escapeHtml(
                        __('The quote list has changed. Please update the negotiated price.')
                    ) ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
</div>
