<?php
?>

<script src="<?= $block->escapeUrl($block->getTrackingUrl()) ?>" async></script>
<script>
    var adminAnalyticsMetadata = {
        "version": "<?= $block->escapeJs($block->getMetadata()->getMagentoVersion()) ?>",
        "user": "<?= $block->escapeJs($block->getMetadata()->getCurrentUser()) ?>",
        "mode": "<?= $block->escapeJs($block->getMetadata()->getMode()) ?>"
    };
</script>
