<?php
?>
<script>
require([
    "prototype",
    "Magento_Sales/order/create/form",
    "Magento_Catalog/catalog/product/composite/configure",
    "domReady!"
], function(){
    order.sidebarHide();
    if (window.productConfigure) {
        productConfigure.addListType('product_to_add', {
            urlFetch: '<?= $block->escapeJs($block->escapeUrl($block->getUrl('sales/order_create/configureProductToAdd'))) ?>'
        });
        productConfigure.addListType('quote_items', {
            urlFetch: '<?= $block->escapeJs($block->escapeUrl($block->getUrl('sales/order_create/configureQuoteItems'))) ?>'
        });
    }
});
</script>
