<?php

/** @var \Magento\NegotiableQuote\Block\Quote\Items $block */

/** @var \Magento\NegotiableQuote\Helper\Quote $quoteHelper */
$quoteHelper = $block->getQuoteHelper();
?>
<?php $quote = $block->getQuote() ?>
<?php $mergedCells = ($block->getTaxHelper()->displayCartBothPrices() ? 2 : 1); ?>
<div class="data item table-wrapper<?= /* @noEscape */ $mergedCells == 2 ? ' detailed' : ''; ?> quote-table<?= /* @noEscape */ $block->isCustomerPriceChanged() ? ' quote-updated' : '' ?>"
     id="items-quoted" data-role="content">
    <div class="quote-title">
        <strong><?= $block->escapeHtml(__('Items Quoted')) ?></strong>
    </div>
    <table id="shopping-cart-table"
           class="items data table quote-table-items">
        <caption role="heading" aria-level="2" class="table-caption">
            <?= $block->escapeHtml(__('Quote Items')) ?>
        </caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Product Name')) ?></span></th>
            <th class="col sku" scope="col"><span><?= $block->escapeHtml(__('SKU')) ?></span></th>
            <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
            <th class="col stock" scope="col"><span><?= $block->escapeHtml(__('Stock')) ?></span></th>
            <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
            <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
            <?php if ($quoteHelper->isSubmitAvailable()) : ?>
                <th class="col delete" scope="col">&nbsp;</th>
            <?php endif ?>
        </tr>
        </thead>
        <?php foreach ($block->getItems() as $item) : ?>
            <?= $block->getItemHtml($item) ?>
        <?php endforeach ?>
    </table>

    <div class="quote-price-block">
        <?= $block->getChildHtml() ?>
    </div>
</div>
